matrix:
    PYTHON_VERSION:
        - 3.4.6
        - 3.5.3
        - 3.6.0

pipeline:
    build:
        image: nathanhoad/gbulb-python:${PYTHON_VERSION}
        commands:
            - python setup.py install
            - pytest
